/********************************************
* VerifWorks Go2UVM App: VW_DVC_Go2UVM
* Automatically generated by VerifWorks's DVC_Go2UVM Riviera Apps 
* Thanks for using VerifWorks products
* Visit http://www.verifworks.com for more 
* Generated on   : 2016-08-31 09:36:32
********************************************/ 


// Generating SystemVerilog interface for module: fifo
// ---------------------------------------------------------
// Using VW_CLK as a text macro for clock 
// If your clock signal is named other than clk, change the macro below
`define VW_CLK clk
interface fifo_if (input logic `VW_CLK);
  logic  [7:0] data_in;
  logic   pop;
  logic   push;
  logic   rst_n;
  logic  [7:0] data_out;
  logic   empty;
  logic   full;
  logic   pop_err_on_empty;
  logic   push_err_on_full;
  // End of interface signals 


  // Start of clocking block definition 
  clocking cb @(posedge `VW_CLK);
    output data_in;
    output pop;
    output push;
    output rst_n;
    input data_out;
    input empty;
    input full;
    input pop_err_on_empty;
    input push_err_on_full;
  endclocking : cb
  // End of clocking block definition 

endinterface : fifo_if
